Repository iotaledger/goshimmer, pull requests merged in 2021-04, with the labels that each got.

#1163 Release v0.5.5
  CHANGELOG.md
  plugins/autopeering/discovery/parameters.go
  plugins/banner/plugin.go
  plugins/database/versioning.go
Labels: do not merge

#982 Feat: Added mapping of BranchIDs using Markers
  .github/workflows/reviewdog.yml
  packages/ledgerstate/branch.go
  packages/ledgerstate/branch_dag.go
  packages/ledgerstate/transaction.go
  packages/ledgerstate/utxo_dag.go
  packages/markers/manager.go
  packages/markers/manager_test.go
  packages/markers/marker.go
  packages/tangle/booker.go
  packages/tangle/booker_scenario_1_test.go
  packages/tangle/booker_scenario_2_test.go
  packages/tangle/booker_scenario_3_test.go
  packages/tangle/booker_test.go
  packages/tangle/images/TestBookerMarkerMappings.html
  packages/tangle/images/TestBookerMarkerMappings.pdf
  packages/tangle/ledgerstate.go
  packages/tangle/message.go
  packages/tangle/message_test.go
  packages/tangle/storage.go
  packages/tangle/tangle.go
  packages/tangle/tangle_test.go
  packages/tangle/testutils.go
  packages/tangle/tipmanager.go
  packages/tangle/tipmanager_test.go
  plugins/dashboard/explorer_routes.go
  plugins/dashboard/faucet_routes.go
  plugins/dashboard/livefeed.go
  plugins/dashboard/payload_handler.go
  plugins/dashboard/plugin.go
  plugins/dashboard/visualizer.go
  plugins/faucet/plugin.go
  plugins/faucet/state_manager.go
  plugins/messagelayer/consensus_plugin.go
  plugins/messagelayer/mana_plugin.go
  plugins/networkdelay/webapi.go
  plugins/webapi/data/plugin.go
  plugins/webapi/drng/collectivebeacon.go
  plugins/webapi/faucet/plugin.go
  plugins/webapi/info/plugin.go
  plugins/webapi/jsonmodels/tangle.go
  plugins/webapi/jsonmodels/webapi.go
  plugins/webapi/message/plugin.go
  plugins/webapi/tools/drng/drng.go
  plugins/webapi/tools/message/approval.go
  plugins/webapi/tools/message/diagnostic_branches.go
  plugins/webapi/tools/message/diagnostic_messages.go
  plugins/webapi/tools/message/diagnostic_utxoDAG.go
  plugins/webapi/tools/message/missing.go
  plugins/webapi/tools/message/orphanage.go
  plugins/webapi/tools/value/objects.go
  plugins/webapi/value/attachments.go
  plugins/webapi/value/sendtransaction.go
Labels: REVIEW PLEASE

#1200 Fix: Always set the BranchID in the MessageMetadata if a Message has two or more PastMarkers
  packages/markers/index.go
  packages/markers/manager.go
  packages/markers/manager_test.go
  packages/markers/marker.go
  packages/markers/sequence.go
  packages/tangle/booker.go
  packages/tangle/booker_test.go
  packages/tangle/storage.go
Labels: REVIEW PLEASE

#1199 Docs/marker update
  docs/specification/003-markers.md
  packages/tangle/images/TestBookerMarkerMappings.md
Labels: REVIEW PLEASE, docs

#1207 WIP Feat improve snapshot
  packages/consensus/fcob/consensusmechanism_test.go
  packages/epochs/manager.go
  packages/ledgerstate/snapshot.go
  packages/ledgerstate/utxo_dag.go
  packages/mana/accessbasevector.go
  packages/mana/basevector.go
  packages/mana/consensusbasevector.go
  packages/mana/consensusbasevector_test.go
  packages/mana/txinfo.go
  packages/mana/weightedbasevector.go
  packages/tangle/approvalweightmanager.go
  packages/tangle/booker.go
  packages/tangle/booker_test.go
  packages/tangle/ledgerstate.go
  packages/tangle/ledgerstate_test.go
  packages/tangle/tangle.go
  packages/tangle/testutils.go
  packages/tangle/tipmanager_test.go
  plugins/core.go
  plugins/messagelayer/approvalweight.go
  plugins/messagelayer/mana_plugin.go
  plugins/messagelayer/plugin.go
  plugins/remotelog/plugin.go
  plugins/webapi.go
  plugins/webapi/epochs/plugin.go
  plugins/webapi/jsonmodels/epochs.go
  snapshot.bin
  tools/docker-network/docker-compose.yml
  tools/genesis-snapshot/.gitignore
  tools/genesis-snapshot/main.go
  tools/integration-tests/assets/7R1itJx5hVuo9w9hjg5cwKFmek4HMSoBDgJZN8hKGxih.bin
  tools/integration-tests/tester/framework/parameters.go
  tools/integration-tests/tester/tests/consensus/consensus_conflicts_test.go
  tools/integration-tests/tester/tests/consensus/consensus_noconflicts_test.go
  tools/integration-tests/tester/tests/mana/mana_test.go
  tools/integration-tests/tester/tests/testutil.go
Labels: DRAFT

#1204 Implement timestamp vote triggering.
  go.mod
  go.sum
  packages/consensus/fcob/consensusmechanism.go
  packages/consensus/fcob/consensusmechanism_test.go
  packages/consensus/fcob/storage.go
  packages/consensus/fcob/timestamp.go
  packages/metrics/events.go
  packages/vote/vote_context.go
  plugins/analysis/dashboard/fpc_conflict.go
  plugins/analysis/dashboard/fpc_livefeed.go
  plugins/analysis/dashboard/fpc_storage.go
  plugins/messagelayer/consensus_plugin.go
  plugins/messagelayer/parameters.go
  plugins/messagelayer/plugin.go
  plugins/prometheus/global_metrics.go
  plugins/webapi/ledgerstate/plugin.go
  plugins/webapi/tools/message/diagnostic_utxoDAG.go
  tools/integration-tests/tester/go.mod
  tools/integration-tests/tester/go.sum
Labels: Green Team, REVIEW PLEASE

#1208 Feat/message timestamp api
  client/message.go
  packages/tangle/messagefactory.go
  packages/tangle/payload/type.go
  packages/tangle/tangle.go
  plugins/webapi/jsonmodels/webapi.go
  plugins/webapi/message/plugin.go
Labels: Green Team

#1212 add delayedRoundStart
  packages/drng/ticker.go
  packages/drng/ticker_test.go
  packages/vote/fpc/fpc.go
  packages/vote/fpc/fpc_test.go
  packages/vote/opinion/opinion.go
  packages/vote/voter.go
  plugins/messagelayer/consensus_plugin.go
  plugins/messagelayer/parameters.go
Labels: REVIEW PLEASE

#1156 initial protocol docs
  docs/application_logic/Protocol_overview_booking.png
  docs/application_logic/Protocol_overview_consensus.png
  docs/application_logic/Protocol_overview_own_message.png
  docs/application_logic/Protocol_overview_received_message.png
  docs/application_logic/protocol.md
Labels: REVIEW PLEASE, docs

#1202 Integrate dRNG with FPC
  docs/tooling/docker_private_network.md
  packages/drng/drng.go
  packages/drng/ticker.go
  packages/drng/ticker_test.go
  packages/prng/unix_ts_rng.go
  packages/vote/fpc/fpc.go
  packages/vote/fpc/fpc_test.go
  packages/vote/opinion/opinion.go
  packages/vote/voter.go
  plugins/drng/plugin.go
  plugins/messagelayer/consensus_plugin.go
  plugins/messagelayer/parameters.go
  tools/docker-network/config.docker.json
  tools/docker-network/docker-compose-drng.yml
  tools/docker-network/run.sh
Labels: REVIEW PLEASE, do not merge

#1233 fix bug
  packages/tangle/messagefactory.go
  packages/tangle/tangle.go
Labels: REVIEW PLEASE

#1232 Feat: Create integration test network with nodes having mana.
  client/faucet.go
  tools/integration-tests/tester/framework/framework.go
  tools/integration-tests/tester/framework/network.go
  tools/integration-tests/tester/framework/parameters.go
  tools/integration-tests/tester/tests/testutil.go
Labels: REVIEW PLEASE
